<?xml version="1.0"?>
<package format="3">
  <name>teleop_ik</name>
  <version>0.1.0</version>
  <description>Franka kinematics, damped least-squares IK and teleoperation nodes.</description>
  <maintainer email="janmesh.4300@gmail.com">Janmesh Patel</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_msgs</depend>
  <depend>std_msgs</depend>
  <depend>eigen</depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
